version: "3"

services:
 web_1:
  container_name: nginx_8085
  image: nginx
  volumes:
   - ./html-8085/:/usr/share/nginx/html
  ports:
   - "8085:80"

 web_2:
  container_name: nginx_8086
  image: nginx
  volumes:
   - ./html-8086/:/usr/share/nginx/html
  ports:
   - "8086:80"   

 web_3:
  container_name: nginx_8087
  image: nginx
  volumes:
   - ./html-8087/:/usr/share/nginx/html
  ports:
   - "8087:80"