version: "3"

services:
 web_1:
  container_name: nginx_8085
  image: nginx
  volumes:
   - ./nginx-8085/html/:/usr/share/nginx/html
   - ./nginx-8085/log/:/var/log/nginx/
  ports:
   - "8085:80"

 web_2:
  container_name: nginx_8086
  image: nginx
  volumes:
   - ./nginx-8086/html/:/usr/share/nginx/html
   - ./nginx-8086/log/:/var/log/nginx/
  ports:
   - "8086:80"   

 web_3:
  container_name: nginx_8087
  image: nginx
  volumes:
   - ./nginx-8087/html/:/usr/share/nginx/html
   - ./nginx-8087/log/:/var/log/nginx/
  ports:
   - "8087:80"