version: "3"

services:
  webapp1:
    container_name: springboot-redis-docker-8083
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8083:8082"
    depends_on:
      - redis

  webapp2:
    container_name: springboot-redis-docker-8084
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8084:8082"
    depends_on:
      - redis

  webapp3:
    container_name: springboot-redis-docker-8085
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8085:8082"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
