version: "3"

services:
  webapp1:
    container_name: webapp-8083
    build: webapp
    restart: on-failure
    ports:
      - "8083:8082"
    depends_on:
      - redis

  webapp2:
    container_name: webapp-8084
    build: webapp
    restart: on-failure
    ports:
      - "8084:8082"
    depends_on:
      - redis

  webapp3:
    container_name: webapp-8085
    build: webapp
    restart: on-failure
    ports:
      - "8085:8082"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  master:
    container_name: master
    image: nginx
    restart: on-failure
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/
    ports:
      - "8089:80"
    depends_on:
      - webapp1
      - webapp2
      - webapp3